### ISSUE TITLE
Add support for {created,updated,deleted}_at

### ISSUE THREAD

**Issue by mmoreaux** [CodeYellowBV/django-binder#29]
Kinda like Laravel.
- If a model has a DateTimeField `created_at`, it is set by Binder at object creation time.
- If a model has a DateTimeField `updated_at`, it is set by Binder whenever the object is updated.
- If a model has a DateTimeFIeld `deleted_at`, this is used by Binder for soft-deletion, replacing the BooleanField `deleted`.

We need to decide how to deal with the current BooleanField `deleted`... Migrate to `deleted_at`, or support both?

**Comment by sjamaan** [comment]
Isn't `created_at`/`updated_at` already handled by [`auto_now_add` / `auto_now`](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.DateField.auto_now) from the `DateTimeField`?

**Comment by mmoreaux** [comment]
Oh wow, didn't know about those :D 

In that case, we should decide on a convention for the names, and decide how (if...) to approach `deleted_at`.

**Comment by mmoreaux** [comment]
This might still require a little work on Binder's part. I'd need to check to be sure, but I'm afraid a `PUT {}` on an object will trigger a save(), which would update the `updated_at` which may or may not be what we want.

Also, we need to check how well this plays together with history.

**Comment by sjamaan** [comment]
I think it works well enough. Please reopen with a more specific scenario if the current behaviour needs to change. `deleted_at` might be nice but is currently not really necessary (typically, if `deleted` is true, `updated_at` will reflect when it was deleted, because there are not many situations in which a deleted object is saved again).
