### ISSUE TITLE
Automagically order by id

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/django-binder#73]
When no sort order is given, strange things might happen. Could we automagically order by id if no order by id is given? So:

`order_by: []` automagically becomes `order_by: [-id]`
`order_by: [last_name]` automagically becomes `order_by: [last_name, -id]`
`order_by: [id]` doesn't change

See also https://github.com/CodeYellowBV/mobx-spine/issues/53.

**Comment by JasperStam** [comment]
It looks like the default sorting already should be on id: 
https://github.com/CodeYellowBV/django-binder/blob/master/binder/models.py#L158

**Comment by SpaceK33z** [comment]
@JasperStam, we know that, but that is not the problem. Burhan is talking about if you set an order in the request, like `?order_by=last_name`. In this case it will be ordered by the last name correctly, however if you have two of the same last names ("Janssen"), it will randomly order those two. This leads to problems with pagination.

In the frontend we can fix that issue by doing `?order_by=lastname,id`; this will guarantee the same order every time. This is a very subtle issue however, and Burhan and I think we should fix Binder to automatically insert the `id` ordering.

**Comment by mmoreaux** [comment]
> however if you have two of the same last names ("Janssen"), it will randomly order those two. This leads to problems with pagination.

Is that true? I would expect the ordering to be undefined but stable between postgres queries. Maybe @sjamaan can comment on this.

I'm not a huge fan of just hardcoding default orderings; adding an order comes at the cost of slower performance. But we can do it if it's necessary.

**Comment by sjamaan** [comment]
> I would expect the ordering to be undefined but stable between postgres queries. Maybe @sjamaan can comment on this.

Postgres is a bit counter-intuitive with this. The query planner will pick the best plan for the query based on its current statistics. So if an autovacuum updates the stats, it may pick a completely different plan. Also, a simple OFFSET may even return a different query as well. So, you should be careful not to make _any_ assumptions about (partial) ordering where you didn't explicitly specify one.

In this case I think it's the sanest to always add ordering by ID at the end of every standard Binder list endpoint. I don't know if `get_queryset()` should do that, because that may be used by custom endpoints too, in which case you might not want any ordering to be added (though that also heavily depends on the use case, I guess).

**Comment by mmoreaux** [comment]
Alright, then we'll add it.

I propose we do so in `ModelView.order_by()`, by appending the default model order (`Model.Meta.ordering`) to the API-provided `order_by`s. That way the default orderings are always active unless explicitly overridden. Setting the default ordering can be done on a per-model basis, and Binder already provides ordering on `id` here by default.

**Comment by sjamaan** [comment]
Sounds good
