### ISSUE TITLE
Filterable relations

### ISSUE THREAD

**Issue by JasperStam** [CodeYellowBV/django-binder#81]
Filtering on relations is currently impossible.
The with syntax also doesn't combine well with the filter syntax.

Use case:
GET zoo with contacts where contacts.name like henk

This wouldn't fit well in the `with` clause, as you can't pass a value in a syntax like: `contacts.name:icontains=val` and it's hard to interpret if `.name` is a relation or a filter

This also wouldn't fit well in the query param filters, as those say something about the target model.

Maybe a `where` clause would be a better idea?

**Comment by mmoreaux** [comment]
First off, I'm a little concerned with the direction this takes; We've observed several times that binder is too generic, and too powerful, with too much control at the FE. Adding stuff like this would make that worse.

For your use case, maybe GET contact ?.name:icontains=henk ?with=zoos is enough? (I doubt it, because I'm sure your _actual_ use case is more complicated than the example)

What would be the syntax of your proposed `where` clause?

**Comment by JasperStam** [comment]
Yes my use case is slightly different:
We have an allocation with A LOT of activities. The frontend wants to show an allocation with only the unfinished activities.

I'm totally not set on this but something like this:
`GET allocation?with=activities&where:activities|.status:not:in=finished`

`where:[relation specifier]|[normal filter syntax]`

**Comment by mmoreaux** [comment]
After some discussion, we came up with these two potential syntaxes:

```
GET zoo ?where=contacts.city(name=ehv) ?with=contacts.city ?with=contacts.school
GET zoo ?.contacts.city(name=ehv) ?with=contacts.city ?with=contacts.school
```
